### ISSUE TITLE
Meteor + Desklamp installation error

### ISSUE THREAD

**Issue by ralphievolt** [desklamp-js/Desklamp.io#12]
i'm trying to install this on my meteor app and act as my router but got an error .. we do this my `meteor npm install --save desklamp` instead of just `npm install --save desklamp` as not to conflict with meteor internal node/npm version

![desklamp error](https://cloud.githubusercontent.com/assets/5282658/20142191/b5875894-a6ce-11e6-8cf3-7c790e3dc14c.png)

i'm not sure if this is an error for meteor or from desklamp

**Comment by ralphievolt** [comment]
i named my app as desklamp so therefore can't install an npm packages with the same name..

**Comment by sneakykate** [comment]
Ah. That happens! Let us know how it goes otherwise. Thanks!

**Comment by ralphievolt** [comment]
Can you make an example integration Desklamp with MeteorJs? Been spending hours to integrate but can't seems to work 

a meteor starter kit could be your starting point.. [https://github.com/karpusa/meteor-less-react-starter-kit](url)

Thanks
